# User.create!([
#   {email: "kimberlylowewilliams@gmail.com", encrypted_password: "$2a$10$1IWU20WpPW8gClAHXL0kyOO6k1YwUNYyhn2t42Y9jrsYdM/B2Kj6e", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 4, current_sign_in_at: "2015-06-12 00:41:55", last_sign_in_at: "2015-06-11 18:39:23", current_sign_in_ip: "::1", last_sign_in_ip: "::1"},
#   {email: "nutafficionado@lovenut.com", encrypted_password: "$2a$10$oEwPWzVJG/CUK/2NolHzWOxrqC96QT4FiLb87MJ/NzR6JG6DjtY3C", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 2, current_sign_in_at: "2015-06-12 00:50:37", last_sign_in_at: "2015-06-12 00:31:26", current_sign_in_ip: "::1", last_sign_in_ip: "::1"}
# ])
Image.create!([
  {image_url: "http://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Pistachios_in_shells.jpg/800px-Pistachios_in_shells.jpg", description: "pistachios1", product_id: 1},
  {image_url: "http://upload.wikimedia.org/wikipedia/commons/3/3c/CashewSnack.jpg", description: "cashews1", product_id: 2},
  {image_url: "http://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Smoked_almonds.JPG/800px-Smoked_almonds.JPG", description: "almonds1", product_id: 3},
  {image_url: "http://www.dfaofca.com/wp-content/uploads/2012/01/walnuts.jpg", description: "walnuts1", product_id: 4},
  {image_url: "http://conway.locallygrown.net/files/product/image/113662/original/photo.jpg?1356485474", description: "pecans1", product_id: 5},
  {image_url: "http://cdn.shopify.com/s/files/1/0275/2899/products/macadamia_nut.jpg?v=1398249626", description: "macadamia1", product_id: 6},
  {image_url: "https://thepaleopact.files.wordpress.com/2014/12/shutterstock_103452743.jpg", description: "brazil1", product_id: 7},
  {image_url: "https://www.thesleuthjournal.com/wp-content/uploads/2015/05/coconut.jpg", description: "coconut1", product_id: 8},
  {image_url: "http://www.bestherbalhealth.com/wp-content/uploads/2014/01/hazelnuts1.jpg", description: "hazelnuts1", product_id: 9},
  {image_url: "http://www.foods-healing-power.com/images/250xNxchestnuts.jpg.pagespeed.ic.6vSGB0ehux.webp", description: "chestnuts1", product_id: 10},
  {image_url: "http://www.americanpistachios.org/sites/default/files/APG-Pistachio_Close_Up.jpg", description: "pistachios2", product_id: 1},
  {image_url: "http://mit-pl.com/wp-content/uploads/2014/05/Cashews.jpg", description: "cashews2", product_id: 2},
  {image_url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTrTkcPraV6sgUkPKhwrT2ml9EG2cM-eEjQv9bN5hwh8MNBVMvyFQ", description: "almomds2", product_id: 3},
  {image_url: "http://www.healthpromoting.com/sites/default/files/imagecache/product_full/Organic%20almonds.jpg", description: "almonds3", product_id: 3},
  {image_url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQGCwQPRmmAgQT25RkWjPxZFoFRNq9HcejZ2cJTbb5ZaxHDtWViwg", description: "walnuts2", product_id: 4},
  {image_url: "http://www.insockmonkeyslippers.com/wp-content/uploads/2011/11/pecans_main.jpg", description: "pecans2", product_id: 5},
  {image_url: "http://ailanigardens.com/wp-content/uploads/2013/11/macadamia-1.jpg", description: "macadamia2", product_id: 6},
  {image_url: "http://brazilimmigration.com/wp-content/uploads/pep-vn/f9d44468/raw-brazil-nuts-fa-849x565.jpg", description: "brazil2", product_id: 7},
  {image_url: "http://coconutoil.com/wp-content/uploads/sites/6/2013/11/coconuts-Coconut-oil-on-spoon.jpg", description: "coconut2", product_id: 8},
  {image_url: "http://www.ou.org/life/files/Hazelnuts.jpg", description: "hazelnuts2", product_id: 9},
  {image_url: "http://www.tasteofbeirut.com/wp-content/uploads/2009/11/MG_1150.JPG", description: "chestnuts2", product_id: 10}
])
Order.create!([
  {quantity: 32, product_id: 2, user_id: 1, total_price: nil, tax: nil, subtotal: nil},
  {quantity: nil, product_id: nil, user_id: nil, total_price: nil, tax: nil, subtotal: nil},
  {quantity: nil, product_id: nil, user_id: nil, total_price: nil, tax: nil, subtotal: nil},
  {quantity: nil, product_id: nil, user_id: nil, total_price: nil, tax: nil, subtotal: nil},
  {quantity: nil, product_id: nil, user_id: nil, total_price: nil, tax: nil, subtotal: nil},
  {quantity: nil, product_id: nil, user_id: nil, total_price: nil, tax: nil, subtotal: nil},
  {quantity: 3, product_id: nil, user_id: nil, total_price: nil, tax: nil, subtotal: nil},
  {quantity: 5, product_id: nil, user_id: nil, total_price: nil, tax: nil, subtotal: nil},
  {quantity: 12, product_id: nil, user_id: nil, total_price: nil, tax: nil, subtotal: nil},
  {quantity: 7, product_id: nil, user_id: nil, total_price: nil, tax: nil, subtotal: nil},
  {quantity: 5, product_id: nil, user_id: nil, total_price: nil, tax: nil, subtotal: nil},
  {quantity: 3, product_id: nil, user_id: nil, total_price: nil, tax: nil, subtotal: nil},
  {quantity: 22, product_id: nil, user_id: 1, total_price: nil, tax: nil, subtotal: nil},
  {quantity: 9, product_id: 5, user_id: 1, total_price: nil, tax: nil, subtotal: nil},
  {quantity: 3, product_id: 6, user_id: 1, total_price: nil, tax: nil, subtotal: nil},
  {quantity: 6, product_id: 6, user_id: 1, total_price: nil, tax: nil, subtotal: nil},
  {quantity: 32, product_id: 2, user_id: 1, total_price: nil, tax: nil, subtotal: nil},
  {quantity: 12, product_id: 2, user_id: 1, total_price: nil, tax: nil, subtotal: nil},
  {quantity: 5, product_id: 2, user_id: 1, total_price: nil, tax: nil, subtotal: nil},
  {quantity: 8, product_id: 2, user_id: 1, total_price: nil, tax: nil, subtotal: nil},
  {quantity: 2, product_id: 9, user_id: 1, total_price: nil, tax: nil, subtotal: nil},
  {quantity: 3, product_id: 9, user_id: 1, total_price: nil, tax: nil, subtotal: nil},
  {quantity: 4, product_id: 9, user_id: 1, total_price: nil, tax: nil, subtotal: nil},
  {quantity: 4, product_id: 9, user_id: 1, total_price: nil, tax: nil, subtotal: nil},
  {quantity: 5, product_id: 9, user_id: 1, total_price: nil, tax: nil, subtotal: nil},
  {quantity: 1, product_id: 10, user_id: 1, total_price: nil, tax: nil, subtotal: nil},
  {quantity: 9, product_id: 10, user_id: 1, total_price: nil, tax: nil, subtotal: nil},
  {quantity: 3, product_id: 7, user_id: 1, total_price: nil, tax: nil, subtotal: nil},
  {quantity: 5, product_id: 5, user_id: 1, total_price: nil, tax: nil, subtotal: nil},
  {quantity: 50, product_id: 2, user_id: 1, total_price: nil, tax: nil, subtotal: 9.0},
  {quantity: 3, product_id: 4, user_id: 1, total_price: nil, tax: nil, subtotal: 0.0},
  {quantity: 66, product_id: 2, user_id: 1, total_price: 143.88, tax: 11.0, subtotal: 132.0},
  {quantity: 3, product_id: 3, user_id: 2, total_price: 6.18, tax: 0.0, subtotal: 5.0},
  {quantity: 5, product_id: 1, user_id: 2, total_price: 9.21, tax: 0.0, subtotal: 8.0},
  {quantity: 10, product_id: 1, user_id: 1, total_price: 18.42, tax: 1.0, subtotal: 16.0},
  {quantity: 12, product_id: 7, user_id: 1, total_price: 27.73, tax: 2.29, subtotal: 25.44},
  {quantity: 3, product_id: 9, user_id: 2, total_price: 10.79, tax: 0.89, subtotal: 9.9}
     ])
Product.create!([
  {name: "pistachios", price: 1.69, description: "This nut is a member of the cashew family, is a small tree originating from Central Asia and the Middle East.", in_stock: nil, supplier_id: 4},
  {name: "cashews", price: 2.0, description: "Cashew nuts are a popular snack and food source. Cashews, unlike other oily tree nuts, contain starch to about 10% of their weight. This makes them more effective than other nuts in thickening water-based dishes such as soups, meat stews, and some Indian milk-based desserts.", in_stock: nil, supplier_id: 2},
  {name: "almonds", price: 1.89, description: "The name of the edible and widely cultivated seed of the almond tree. Touted to reduce risk of cancer.", in_stock: nil, supplier_id: 1},
  {name: "walnuts", price: 1.29, description: "A walnut is the nut of any tree of the genus Juglans (Family Juglandaceae), particularly the Persian or English walnut, Juglans regia. It is used for food after being processed while green for pickled walnuts or after full ripening for its nutmeat.", in_stock: nil, supplier_id: 2},
  {name: "pecans", price: 1.89, description: "a species of hickory native to Mexico and the southcentral and southeastern regions of the United States.[1][2]  \"Pecan\" is from an Algonquian word meaning a nut requiring a stone to crack.", in_stock: nil, supplier_id: 3},
  {name: "Macadamia", price: 3.0, description: "Great for the skin.", in_stock: nil, supplier_id: 4},
  {name: "Brazil Nuts", price: 2.12, description: "Brazil nuts are high in calories, contain good quantities of vitamins, anti-oxidants and minerals. Its kernels, in-fact, have been staple energy sources of native Amazonians even today.", in_stock: nil, supplier_id: 4},
  {name: "Coconut", price: 4.15, description: "They're everywhere.", in_stock: nil, supplier_id: 4},
  {name: "Hazelnuts", price: 3.3, description: "Giselle's favorite yet to be discovered.", in_stock: nil, supplier_id: 3},
  {name: "Chestnuts", price: 2.5, description: "Chestnuts are the only low-fat nuts, with a fraction of the calories of other types of nuts. They contain just 1 gram of fat and a little less than 70 calories per 30 grams of dried or roasted nuts.", in_stock: nil, supplier_id: 1}
])
Supplier.create!([
  {name: "HBS Foods LTD", email: "info@hbsfoods.co.uk", phone: "01384 457705"},
  {name: "Kanegrade", email: "info@kanegrade.com", phone: "+44 (0)1438 742 242"},
  {name: "Almans", email: "info@almans.com", phone: "+27 11 397 4685"},
  {name: "Bega Nuts", email: "info@beganuts.com", phone: "(65) 6448 5612"}
])
